// Questions par défaut chargeables depuis l'admin via le bouton "Charger les questions par défaut"
// À ajuster ensuite directement dans l'interface admin selon ce que tu veux.

export const defaultQuestions = [
  {
    id: 'lame-sang',
    name: 'Lame de sang',
    prompt: 'Que peut-on observer sur cette lame ?',
    choices: ['Sang', 'Salive', 'Cellules de peau', 'Tissu musculaire'],
    correctAnswer: 'Sang',
    order: 1,
  },
  {
    id: 'lame-pollen-carex',
    name: 'Lame de pollen de carex',
    prompt: 'À quelle plante appartient ce pollen ?',
    choices: ['Carex', 'Chêne', 'Pin', 'Tournesol'],
    correctAnswer: 'Carex',
    order: 2,
  },
  {
    id: 'lame-pollen-chene',
    name: 'Lame de pollen de chêne',
    prompt: 'À quelle plante appartient ce pollen ?',
    choices: ['Chêne', 'Carex', 'Lavande', 'Bouleau'],
    correctAnswer: 'Chêne',
    order: 3,
  },
  {
    id: 'lame-branchie-poisson',
    name: 'Lame de branchie de poisson',
    prompt: 'Quel organe peut-on observer sur cette lame ?',
    choices: ['Branchie de poisson', 'Poumon', 'Foie', 'Estomac'],
    correctAnswer: 'Branchie de poisson',
    order: 4,
  },
  {
    id: 'crane-cheval',
    name: 'Crâne de cheval',
    prompt: 'À quelle espèce appartient ce crâne ?',
    choices: ['Cheval', 'Vache', 'Chien', 'Sanglier'],
    correctAnswer: 'Cheval',
    order: 5,
  },
  {
    id: 'crane-vache',
    name: 'Crâne de vache',
    prompt: 'À quelle espèce appartient ce crâne ?',
    choices: ['Vache', 'Cheval', 'Cerf', 'Mouton'],
    correctAnswer: 'Vache',
    order: 6,
  },
  {
    id: 'crane-pigeon',
    name: 'Crâne de pigeon',
    prompt: 'À quelle espèce appartient ce crâne ?',
    choices: ['Pigeon', 'Corneille', 'Pie', 'Mouette'],
    correctAnswer: 'Pigeon',
    order: 7,
  },
  {
    id: 'crane-lapin',
    name: 'Crâne de lapin',
    prompt: 'À quelle espèce appartient ce crâne ?',
    choices: ['Lapin', 'Lièvre', 'Rat', 'Hamster'],
    correctAnswer: 'Lapin',
    order: 8,
  },
  {
    id: 'crane-chat',
    name: 'Crâne de chat',
    prompt: 'À quelle espèce appartient ce crâne ?',
    choices: ['Chat', 'Renard', 'Furet', 'Chien'],
    correctAnswer: 'Chat',
    order: 9,
  },
  {
    id: 'fossile-ammonite',
    name: 'Fossile d\'ammonite',
    prompt: 'Quel fossile est-ce ?',
    choices: ['Ammonite', 'Bélemnite', 'Trilobite', 'Coquille d\'huître'],
    correctAnswer: 'Ammonite',
    order: 10,
  },
  {
    id: 'fossile-fougere',
    name: 'Fossile de fougère',
    prompt: 'Quel fossile est-ce ?',
    choices: ['Fougère', 'Algue', 'Coraux', 'Mousse'],
    correctAnswer: 'Fougère',
    order: 11,
  },
  {
    id: 'fossile-coraux',
    name: 'Fossile de coraux',
    prompt: 'Quel fossile est-ce ?',
    choices: ['Coraux', 'Éponge', 'Algue calcaire', 'Bryozoaire'],
    correctAnswer: 'Coraux',
    order: 12,
  },
  {
    id: 'fossile-belemnite',
    name: 'Fossile de bélemnite',
    prompt: 'Quel fossile est-ce ?',
    choices: ['Bélemnite', 'Ammonite', 'Os', 'Dent de requin'],
    correctAnswer: 'Bélemnite',
    order: 13,
  },
  {
    id: 'fossile-trilobite',
    name: 'Fossile de trilobite',
    prompt: 'Quel fossile est-ce ?',
    choices: ['Trilobite', 'Crustacé moderne', 'Insecte', 'Mille-pattes'],
    correctAnswer: 'Trilobite',
    order: 14,
  },
]
